# Generated by Django 4.1.7 on 2023-05-01 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(default='', max_length=30, verbose_name='имя')),
                ('car_brand', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'машины',
                'verbose_name_plural': 'машины',
            },
        ),
        migrations.CreateModel(
            name='CarInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('engine_capacity', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('fuelCriteria', models.SmallIntegerField(choices=[(1, 'бензин'), (2, 'дизель'), (3, 'газ')], default=1)),
                ('yearOfRelease', models.IntegerField(default=0)),
                ('wheelLocation', models.CharField(default='', max_length=30)),
                ('color', models.CharField(default='', max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avtosalon.car')),
            ],
            options={
                'verbose_name': 'информация о машинах',
                'verbose_name_plural': 'информация о машинах',
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showroomName', models.CharField(default='', max_length=25, verbose_name='имя')),
                ('location', models.CharField(max_length=35, verbose_name='местоположение')),
                ('cars', models.ManyToManyField(through='avtosalon.CarInformation', to='avtosalon.car')),
            ],
            options={
                'verbose_name': 'автосалон',
                'verbose_name_plural': 'автосалон',
            },
        ),
        migrations.AddField(
            model_name='carinformation',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avtosalon.showroom'),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerName', models.CharField(default='', max_length=30)),
                ('price', models.IntegerField(default=0, verbose_name='цена')),
                ('date', models.DateTimeField(default='')),
                ('purchases', models.ManyToManyField(related_name='покупки', to='avtosalon.car', verbose_name='покупки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'покупатель',
                'verbose_name_plural': 'покупатель',
            },
        ),
    ]
